### ISSUE TITLE
add other language(s)?

### ISSUE THREAD

**Issue by 2254FB** [Clownacy/CSE2#123]
- for the accurate branch:
I tried to replace the game_japanese/data folder with the chinese version Cave Story's data folder and compiled it with -DJAPANESE=ON, the in game dialog seems fine but the title and other text is not displayed properly,but it shouldn't be hard to fix.I haven't check all the code,it's seems extra work is needed to add other languages.Could anybody help?

- for the other branch:
It seems that some of the resource has been updated,and some extra resource has been added.Has no idea of how to convert the original data.

Besides,I think it's strange to save exactly same resource in different language folder multi times.for the common files,I think it's better to move to other folder,and only the different resource should be in the language folder.

**Comment by Clownacy** [comment]
It sounds like the Chinese version modifies the `Doukutsu.exe` file, and not just the data folder. Whatever modifications the Chinese version has would have to be reverse-engineered and applied to CSE2.

Also, CSE2 is based on Cave Story v1.0.0.6. I've heard that there's a v1.0.0.7 version, which was specifically made to improve Chinese-language support. I do plan on finding the differences between those two versions, and adding v1.0.0.7 to CSE2, but that's a long way away. Without those changes, supporting Chinese might not be possible.

**Comment by 2254FB** [comment]
I checked the lastet Chinese version,it's still v1.0.0.6.
![image](https://user-images.githubusercontent.com/40604180/82897221-de788e00-9f89-11ea-8317-d3ecf54338f2.png)
download link: [https://pawism.com/sp/doukutsu/pub/dou_sc102.zip](url)

I'll try to contact the maintainer of Chinese version and find out what I can do.

**Comment by Riteo** [comment]
I'm trying also to add the italian version.
Are there any licensing issues with those translations?

**Comment by Clownacy** [comment]
I think all translations are technically still under copyright - even the Aeon Genesis one.

**Comment by BetaRays** [comment]
Most translations patch the game to use a different encoding and modify the `*.tsc` files (and sometimes images), they can be converted to and from text using a tool like [vtsc](http://www.cavestory.org/downloads/vtsc.py.zip), if the encoding is changed to UTF-8 (using `iconv -f someencoding -t UTF-8 …` for example), CSE2 should be able to display them correctly. This might even be the case for the japanese version, I don't know if there are any other changes needed to make it work.

**Comment by 2254FB** [comment]
> I think all translations are technically still under copyright - even the Aeon Genesis one.

The maintainer of Chinese version said it's fine to add chinese translation to CSE2,didn't give specific license though.

**Comment by Clownacy** [comment]
Thanks, but I'd prefer multilingual support be handled by a fork, maintained by someone who's familiar with this kind of thing. Just supporting English and Japanese is already too much for me:

The most recent release of CSE2 was supposed to come with modified cutscenes that supported widescreen, but, while the guy that was working on it was able to convert the English cutscenes, he had trouble converting the Japanese ones. Also, the newly-added settings menu lacks a Japanese translation. Extra languages are a maintenance burden, and I don't want to support more than I have to.

The reason there's a Japanese language option is because it's Cave Story's original language, and it's needed for the accurate branch to produce an accurate EXE. Meanwhile, there's an English option because CSE2 was made for the English-speaking Cave Story modding community.

**Comment by 2254FB** [comment]
> Thanks, but I'd prefer multilingual support be handled by a fork, maintained by someone who's familiar with this kind of thing. Just supporting English and Japanese is already too much for me:
> 
> The most recent release of CSE2 was supposed to come with modified cutscenes that supported widescreen, but, while the guy that was working on it was able to convert the English cutscenes, he had trouble converting the Japanese ones. Also, the newly-added settings menu lacks a Japanese translation. Extra languages are a maintenance burden, and I don't want to support more than I have to.
> 
> The reason there's a Japanese language option is because it's Cave Story's original language, and it's needed for the accurate branch to produce an accurate EXE. Meanwhile, there's an English option because CSE2 was made for the English-speaking Cave Story modding community.

I think i18n is an import feature,especially as this project is called an 'Engine'.Adding other languges doesn't mean you should maintain these language, but add a interface or something that makes people easier to add other languages.

In fact,I did some research and fixed all the text glitch in the accurate branch,now it can launch in totoally Chinese.It didn't take me a long time, just as I expected.For the other branch I'll check later.Just as I mentioned before,I think i18n is a necessary feature.I'm not asking you to add Chinese and maintain it,but hoping the i18n can be improved and make it easier for people to add and maintain other languages.

It's a great project and Thank you(and other guys) for your great work.

**Comment by Clownacy** [comment]
[The enhanced branches have been discontinued.](https://www.cavestory.org/forums/threads/cse2-the-cave-story-decompilation-project.14657/page-7#post-374158) Thank you for your interest in the project.
