### ISSUE TITLE
Bring Back The CS Arranged Soundtrack From The Mod Loader Days

### ISSUE THREAD

**Issue by AlxWolfenstein97** [Clownacy/CSE2#125]
Allow people to have that one as another soundtrack option by supporting and linking to this in-game version @ https://www.reddit.com/r/cavestory/comments/9rz3p4/im_not_really_sure_where_to_post_this_but_i_made/

**Comment by Clownacy** [comment]
Added in 0cd5d41882dbf14e37ef199ce9fb01f58c6469bb.
