### ISSUE TITLE
Allow mirroring gamepad shoulder and trigger buttons

### ISSUE THREAD

**Issue by vaguerant** [Clownacy/CSE2#129]
My experience is with the Wii U port, but I think most of this applies to any gamepad with two sets of L/R buttons.

In the Wii U version, weapon cycling currently defaults to ZL and ZR, while the L and R buttons serve no purpose. If the user prefers, they can remap those functions to the L/R buttons, but I think it would be a huge boost to convenience if an option could be added specifically to have L/ZL and R/ZR share functionality instead.

This could be an option in the control menu like "mirror shoulder buttons" or similar, which wouldn't otherwise need to change how input works, it would just have L/ZL behave as a single button, e.g. user selects "Next Weapon" and is prompted to press a button, they press R and the mapping is set to "R/ZR".

The reason I think this would be useful is because there's such a wide variety of controllers you can use with a Wii U, and the shoulder button layout can vary pretty dramatically between them. On the Wii U GamePad, the fingers naturally rest on ZL/ZR, but on a Wii Classic Controller, it's far more comfortable to press the L/R buttons. On the Nintendo-licensed Hori Battle Pad, the shoulder and trigger placements are inverted, with L/R taking the rear position and ZL/ZR in the front. Taking it a step further, the SNES Classic Mini controller (recognized as a Wii Classic Controller on Wii U) doesn't even have ZL/ZR buttons.

Remapping the controls any time you change controllers seems like overkill for this situation, especially in a game like Cave Story where any modern controller has *way* more buttons than you actually need, so doubling up some inputs makes total sense to me.

**Comment by Clownacy** [comment]
I think a proper solution would be to allow multiple keys to be bound to the same action. The trouble is, I can't think of a way to implement it that doesn't make the rebinding menu extremely clunky.

**Comment by vaguerant** [comment]
Haha, yeah, initially I was going to call this issue "allow mapping multiple buttons to the same function" but I could immediately see how much worse that would have made the control remapping menu. The emulator PPSSPP probably has the most robust multi-mapping menu I can think of and it works fairly reasonably:

![Screenshot_2013-12-20-09-39-12](https://user-images.githubusercontent.com/5259025/84772115-d6a68980-b01d-11ea-9647-6506aae2cc1d.png)

Changing the buttons works pretty similarly to CSE2, with the addition being those on-screen X and + buttons on the right side, which are how you remove or add additional inputs. So you'd map the button once, then hit the plus sign to add a second input for the same function. It's not as clean as CSE2, but for flexibility it's probably the best approach I've seen.

**Comment by Clownacy** [comment]
[The enhanced branches have been discontinued.](https://www.cavestory.org/forums/threads/cse2-the-cave-story-decompilation-project.14657/page-7#post-374158) Thank you for your interest in the project.

This issue might be migrated to CSE2EX, since I don't plan on scraping the controller rebinding there.
