### ISSUE TITLE
enhanced-lite: NPC/Bullet/Effect arrays are fixed-size

### ISSUE THREAD

**Issue by GabrielRavier** [Clownacy/CSE2#135]
The arrays used for NPCs, bullets and effects (and some others) are of a fixed size. Making them extensible (through the use of something like `std::deque` or `std::vector` (`std::vector` only for arrays for which nothing keeps pointers to individual elements)) would make it possible to use an arbitrary amount of NPCs/bullets/effects/etc., which would be nice.

**Comment by Clownacy** [comment]
Personally, I'd probably implement this as a C-style linked-list. Though, I'm still trying to figure-out how to handle `SetNpChar`'s last parameter - it's used as an index into the NPC array.

Maybe I'll make it into a 'priority' variable of the `NPCHAR` struct, and have `SetNpChar` sort the array based on that - so NPCs with it set to 0x100 go after the ones with it set to 0, and before ones set to 0x180. Then, when a new 0x100 NPC is created, it goes after the existing 0x100 NPCs, mimicking the original behaviour almost exactly.

The only differing behaviour would be the original side-effect of the array filling, causing 0 NPCs to sometimes be allocated after existing 0x100 NPCs, presumably breaking layering.

**Comment by GabrielRavier** [comment]
Personally, I'd have highly preferred to use something like `std::list`/`std::deque`/`std::vector` considering how unwieldy to use linked lists are. The only reason I didn't just make this a PR was indeed, as you pointed out, the `SetNpChar` problem. If the solution with sorting would work, I could just make a PR with that. What exactly would be the problem with layering here ? NPCs with priority 0 would just be inserted in between the end of other NPCs with priority 0 and NPCs with higher priority, right ?

**Comment by Clownacy** [comment]
Whoops, I mean that the _original_ behaviour could break layering.

**Comment by Clownacy** [comment]
The enhanced branches have been discontinued.
