### ISSUE TITLE
(enhanced) Feature Request: Support Custom Resolutions

### ISSUE THREAD

**Issue by SeongGino** [Clownacy/CSE2#141]
(Alternative titles: "Support 3:2 resolutions", "Support non-16:9 aspect ratios for Widescreen")

Currently the target hardware I'm running CSE2 on uses a 3:2 display with a resolution of 480x320. While it runs nice and all (using GLES for rendering, though I imagine this affects all render backends), the image looks squished due to top/bottom pillarboxes that try to accommodate for a 16:9 game resolution. And all the windowed resolutions seem to fit that general narrative; of only being made to run at 16:9.

I acknowledge that perhaps running at a non-multiple resolution might cause some strangeness for small rooms (at the very least, vertically speaking), but such a tradeoff would be welcome for what could otherwise be a pixel-perfect display that fills the whole screen on niche devices that don't use common resolutions, or even common aspect ratios. Perhaps it could be invoked via command line option (since `Config.dat`, for all intents and purposes, isn't human- nor Notepad/`nano`-readable for direct modification).
One alternative, if the above isn't possible/satisfactory, could be to use the same resolution standard/aspect ratio as the `accurate` branch - i.e. 4:3 at multiples of 240p. Left/rightmost pillar boxes would be much more preferable on a small display than the cinema-style top/bottom ones we have now.

**Comment by Clownacy** [comment]
[The enhanced branches have been discontinued.](https://www.cavestory.org/forums/threads/cse2-the-cave-story-decompilation-project.14657/page-7#post-374158) Thank you for your interest in the project.
