### ISSUE TITLE
Fix bkMoon and bkFog for higher resolutions in enhanced

### ISSUE THREAD

**Issue by Aarmaster11** [Clownacy/CSE2#94]
Currently, CSE2-enhanced has a small issue with bkMoon and bkFog. When the internal render height is increased, the bottom of the screen shows a gap. Ideally, I think the last line of pixels should be duplicated over this area (and possibly the background centered?).
![image](https://user-images.githubusercontent.com/1887380/73144483-220eca00-4074-11ea-9f98-3ba73029ffcb.png)

Additionally, bkMoon shows two moons due to the background repeating. I think this background style would easily be fixed by utilizing a similar method to Nicalis' in Cave Story+:
![image](https://user-images.githubusercontent.com/1887380/73144421-8da46780-4073-11ea-8b36-f1e833ee2932.png)

**Comment by Clownacy** [comment]
...There _should_ have been a code-based fix for the double-moon thing already in CSE2E. Guess it was broken at some point.

**Comment by Clownacy** [comment]
![](https://cdn.discordapp.com/attachments/544651758283259904/678625949075505152/unknown.png)

Seems to repeat properly for me. Though it should break if the game uses bkMoon with bkFog's background type.

**Comment by Clownacy** [comment]
[The enhanced branches have been discontinued.](https://www.cavestory.org/forums/threads/cse2-the-cave-story-decompilation-project.14657/page-7#post-374158) Thank you for your interest in the project.
